version: "3.9"
services:
  app:
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
    - .:/app:delegated
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: