version: "3.9"
services:
  app:
    build: .
    ports:
      - ${APP_PORT-8000}:${APP_PORT-8000}
    environment:
      MONGO_URI: mongodb://root:rootpassword@mongodb:27017
      APP_PORT: 8000
    depends_on:
      - mongodb
    volumes:
    - .:/app:delegated
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: